// ============================================================
// FIREBASE CONFIGURATION
// ============================================================
// WEEK 3: Replace the placeholder values below with YOUR
// Firebase project config from:
//   Firebase Console > Project Settings > Your Apps > Web App
//
// DO NOT edit this file until Week 3 (Deliverable 3).
// ============================================================

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyAtZNHwx6NPPmmJFwr8c2rKNIa7yGxsm-U",
  authDomain: "masons-menu.firebaseapp.com",
  projectId: "masons-menu",
  storageBucket: "masons-menu.firebasestorage.app",
  messagingSenderId: "221310944762",
  appId: "1:221310944762:web:6652cc0fc2ccdfcbb51043",
  measurementId: "G-R7BLL73GZ1"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firestore and export it
export const db = getFirestore(app);
